test(refactored): Vol 4817 remove servicemanager
dvsa/olcs-selfserve pull request #48
Opened 2024-02-02 12:11 UTC by sanakhandvsa

## Description
Refactoring of duplicated code without loss of test coverage or functionality specific to getServiceManager and getRealServiceManager in various places. 

Related issue: [JIRA_TICKET_NUMBER](LINK_TO_JIRA_TICKET)

## Before submitting (or marking as "ready for review")

- [ ] Does the pull request title follow the [conventional commit](https://www.conventionalcommits.org/en/v1.0.0/) specification?
- [ ] Have you performed a self-review of the code
- [ ] Have you have added tests that prove the fix or feature is effective and working
- [ ] Did you make sure to update any documentation relating to this change?

2024-02-08 14:03 UTC, JoshuaLicense requested changes

2024-02-08 14:03 UTC, JoshuaLicense commented on test/Olcs/src/Controller/Licence/Vehicle/SwitchBoardControllerTest.php
> +        ])->andReturn($this->formValidatorMock);
Isn't `$container` a local variable? What's going on here?

2024-02-09 14:59 UTC, sanakhandvsa commented on test/Olcs/src/Controller/Auth/LoginControllerTest.php
> +        $this->setUpDefaultServices();
**Consistency with Factory Structure**: The structure of the setUpSut method mirrors the `LoginControllerFactory` invocation method.

2024-02-09 15:08 UTC, JoshuaLicense commented on test/Olcs/src/Controller/Auth/LoginControllerTest.php
> +        $this->setUpDefaultServices();
I'm more getting at that this method is not doing anything as it's creating a _local_ variable (`container`, & `controllerPluginManagerMock`), configuring it, and then not using it.

2024-02-09 15:09 UTC, sanakhandvsa commented on test/Olcs/src/Controller/Auth/LoginControllerTest.php
> +        assert($this->authChallengeContainerMock instanceof MockInterface);
The addition of the assert statement directly on the `$this->authChallengeContainerMock` was intended to maintain the same level of integrity and assurance in our tests as previously achieved, but in a more direct and simplified manner. The original code fetched an instance from the `serviceManager` and then used an assert to ensure it was of the correct type. My intention was to replicate this assertion to confirm the mock object's type without the intermediary step of retrieving it from the serviceManager.

2024-02-12 11:32 UTC, sanakhandvsa commented on test/Olcs/src/Controller/Licence/Vehicle/SwitchBoardControllerTest.php
> +        $this->flashMessengerMock->shouldReceive('getMessages')->withAnyArgs();
When we used the ServiceManager, it possibly provided actual instances or lenient mocks (like FlashMessenger) that didn't enforce strict expectations for method calls. After switching to Mockery, we must explicitly define all mock interactions, enhancing test specificity but requiring us to set clear expectations for each method call.

`Received Mockery_3_Laminas_Mvc_Plugin_FlashMessenger_FlashMessenger::hasMessages()`
if not it is giving error no expectations were specified

2024-02-12 12:05 UTC, sanakhandvsa commented on test/Olcs/src/Controller/Licence/Vehicle/SwitchBoardControllerTest.php
> +    protected function formValidator()
- **formValidatorMock** is initialized as a property to provide a mock object that can be utilized across tests.
- Within the **formValidator** method, we're invoking the **isValid** method of the mock object to set expectations specific to that method.

2024-02-12 12:14 UTC, sanakhandvsa commented on test/Olcs/src/Controller/Auth/LoginControllerTest.php
> +        );
Yes Good suggestion, I will  modify where ever in test file separating initialisation after configuring the injected mocks

2024-02-12 12:43 UTC, sanakhandvsa commented on test/Olcs/src/Controller/Licence/Vehicle/SwitchBoardControllerTest.php
> +        ])->andReturn($this->formValidatorMock);
removed

2024-02-22 22:04 UTC, JoshuaLicense approved these changes
Looks good! Thanks @sanakhandvsa!

2024-02-23 12:50 UTC, fibble approved these changes

2024-02-23 14:41 UTC, merged